version: '3.9'

services:
  api:
    networks:
      - fullstack
    restart: always
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db
    links:
      - db
      - minio

  db:
    build:
      context: ../postgres
      dockerfile: ../postgres/Dockerfile
    restart: always
    networks:
      - fullstack
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - memeclub_postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9091"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - "9000:9000"
      - "9091:9091"
    networks:
      - fullstack
    volumes:
      - minio_volume:/data

volumes:
  minio_volume:
    external: true
  memeclub_postgres:
    external: true


networks:
  fullstack:
    driver: bridge